- job:
    name: ansible-role-ssh
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-ssh

- job:
    name: ansible-role-ssh-fedora-latest
    parent: ansible-role-ssh
    nodeset: fedora-latest

- job:
    name: ansible-role-ssh-ubuntu-bionic
    parent: ansible-role-ssh
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-ssh-fedora-latest
        - ansible-role-ssh-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-ssh-fedora-latest
        - ansible-role-ssh-ubuntu-bionic
        - tox-linters
